[package]
name = "QuickShift"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.5"
rayon = "1.10"
anyhow = "1.0"
indicatif = "0.17"

# Windows 长路径支持
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["fileapi", "handleapi", "minwinbase"] }